### ISSUE TITLE
missing redis method on database object

### ISSUE THREAD

**Issue by tsubery** [causes/mock_redis#97]
Hi,

I've noticed an incompatibility between redis-rb and mock-redis. I wrote a method that uses a database connection ".redis" method to reach the redis object. It works fine on production/development but doesn't work in testing env due to missing method in mock redis. I fixed the problem in a fork on my account. 
https://github.com/tsubery/mock_redis/tree/expose_redis_object
Should I make a pull request?

Any other feedback is welcome.
Thanks!

**Comment by sds** [comment]
Hey @tsubery,

Any pull request that brings us closer to the behavior of `redis-rb` is more than welcome!

I'd be happy to merge the feature you describe.

**Comment by sds** [comment]
We decided in #98 that this was not actually part of the `redis-rb` gem, but a third-party integration.
