### ISSUE TITLE
Supporting pubsub commands

### ISSUE THREAD

**Issue by scomma** [causes/mock_redis#99]
Hi, one of my tests expect the `publish` command to work (or at least not fail.) If I modify so it "supports" `publish` and `subscribe`, in the sense that `publish` is a no-op and `subscribe` raises `MockRedis::WouldBlock`, would you entertain the pull request?

**Comment by sds** [comment]
Hey @scomma, I'm fine with this approach as you've described.

Looking forward to the PR!

**Comment by scomma** [comment]
Cool, I'll go work on it!
